foot_traffic_source: "connectors.foot_traffic.OSMPOIAdapter"
# You can add adapter-specific settings:
osm_tags:
  amenity: cafe
week_start: "2025-06-01"

demographics_source: "connectors.demographics.CensusACSAdapter"
acs_year: 2021
state_fips: "06"
county_fips: "075"

competitor_source: "connectors.competitors.OSMCompetitorAdapter"
competitor_place: "Austin, Texas, USA"
competitor_tags:
  shop: True